---
  - hosts: db

    gather_facts: yes

    become: true

    tasks:

    - name: import key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present
    - name: add mongodb repo
      apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' state=present
    - name: install mongodb
      apt: pkg=mongodb-org state=latest update_cache=yes
    - name:
      shell: sudo sed -i "s,\\(^[[:blank:]]*bindIp:\\) .*,\\1 0.0.0.0," /etc/mongod.conf


    - name: MongoDB - Running state
      service:
        name: mongod
        state: started
      ignore_errors: yes

    handlers:
      - name: restart mongodb
        service: name=mongodb state=restarted
