---
  - hosts: web

    gather_facts: yes

    become: true

    tasks:

    - name: Copy Directory APP
      synchronize:
        src: /home/vagrant/iac_ansible1011/app/
        dest: /home/vagrant/app
    - name: Copy Directory Nginx conf
      copy:
        src: /home/vagrant/iac_ansible1011/environment/nginx
        dest: /home/vagrant/environment/config/nginx
