- hosts: web
# host is to define the name of your host machine, group or all servers
# in this example we are targeting server called web

  gather_facts: yes
# gethering facts before performing any tasks

  become: true
# become is used to get root permission to perform any tasks that may require admin access
# set variables
  vars:
    NODEJS_VERSION: "6"
    ansible_distribution_release: "bionic" #trusty
  tasks:
#Tasks are executed in order, one at a time, against all Servers matched by the host pattern
# Every task should have a name, which is included in the output from running the playbook
# The goal of each task is to execute a module, with very specific arguments.

    - name: Install NGINX From Apt-Get
      become: yes
      apt:
        name: nginx
        state: present

    - name: Disable NGINX Default Virtual Host
      become: yes
      command:
        cmd: unlink /etc/nginx/sites-enabled/default

    - name: Create NGINX Conf File
      become: yes
      file:
        path: /etc/nginx/sites-available/rev_proxy.conf
        state: touch

    - name: Amend NGINX Conf File
      become: yes
      blockinfile:
          path: /etc/nginx/sites-available/rev_proxy.conf
          marker: ""
          block: |
            server {
                listen 80;
                location / {
                    proxy_pass http://127.0.0.1:3000;
                    proxy_set_header Authorization "";
                    proxy_read_timeout 90s;
                }
            }

    - name: Link NGINX Reverse Proxy
      become: yes
      command:
        cmd: ln -s /etc/nginx/sites-available/rev_proxy.conf /etc/nginx/sites-enabled/rev_proxy.conf

    - name: Make Sure NGINX Service Is Running
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: yes
